---
openapi: 3.0.1
info:
  title: defaultTitle
  description: defaultDescription
  version: "0.1"
servers:
- url: http://localhost:3001
paths:
  /login:
    post:
      description: Login to get TOKEN to use API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_body'
            examples:
              "0":
                value: '{"email": "s6204062616316@email.kmutnb.ac.th","password": "0859150757"}'
      responses:
        "200":
          description: All Header data
          content:
            application/json; charset=utf-8:
              examples:
                "0":
                  value: '{"accessToken":"Token"}'
      servers:
      - url: http://localhost:3001
    servers:
    - url: http://localhost:3001
  /root-equation:
    get:
      description: Get Data form root-equation
      responses:
        "200":
          description: Data form SubHeader
          content:
            application/json; charset=utf-8:
              examples:
                "0":
                  value: '{"root-equation":{"bisection":[{"id":1,"problem":"x^4-13"},{"id":2,"problem":"x^2-20"}],"falsePosition":[{"id":1,"problem":"x^6-17"},{"id":2,"problem":"x^10-1"}],"onePoint":[{"id":1,"problem":"-e^(x/4)+2"}],"newtonRaphson":[{"id":1,"problem":"7-(x^2)"}]}}'
      servers:
      - url: http://localhost:6061
    servers:
    - url: http://localhost:6061
  /linear:
    get:
      description: Get Data form Linear
      responses:
        "200":
          description: Data form SubHeader
          content:
            application/json; charset=utf-8:
              examples:
                "0":
                  value: '{"linear":{"cramerRule":[{"id":1,"matrixA":"[[-2, 3, 1],[3, 4, -5],[1, -2, 1]]","matrixB":"[9, 0, -4]"},{"id":2,"matrixA":"[[5, 2, 0, 0],[2, 5, 2, 0],[0, 2, 5, 2],[0, 0, 2, 5]]","matrixB":"[12, 17, 14, 7]"}],"gaussElimination":[{"id":1,"matrixA":"[[-2, 3, 1],[3, 4, -5],[1, -2, 1]]","matrixB":"[9, 0, -4]"},{"id":2,"matrixA":"[[5, 2, 0, 0],[2, 5, 2, 0],[0, 2, 5, 2],[0, 0, 2, 5]]","matrixB":"[12, 17, 14, 7]"}]}}'
      servers:
      - url: http://localhost:6061
    servers:
    - url: http://localhost:6061
components:
  schemas:
    login_body:
      type: object
      properties:
        password:
          type: string
        email:
          type: string
